# =============================================================================
# Employee Analytics Data Warehouse
# =============================================================================
# This dbt project transforms raw employee data into analytics-ready tables
# using various incremental strategies (merge, delete+insert, append).
#
# Features:
# - SCD Type 2 snapshots for historical tracking
# - Custom data quality tests
# - Audit logging and observability
# - Reference data via seeds
# =============================================================================

name: 'employee_analytics'
version: '2.0.0'
config-version: 2

# =============================================================================
# Variables
# =============================================================================
vars:
  # Execution date for incremental loads (can be overridden at runtime)
  execution_date: '2022-09-01'
  
  # Data quality thresholds
  max_null_percentage: 5
  min_row_count: 1

# =============================================================================
# Profile Configuration
# =============================================================================
profile: 'employee_analytics'

# =============================================================================
# Directory Configurations
# =============================================================================
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# =============================================================================
# Query Configuration
# =============================================================================
query-comment:
  comment: "dbt run by {{ target.name }} | model: {{ node.name }}"
  append: true

# =============================================================================
# Snapshot Configuration
# =============================================================================
snapshots:
  employee_analytics:
    +target_schema: dev

# =============================================================================
# Seed Configuration  
# =============================================================================
seeds:
  employee_analytics:
    +schema: dev
    +quote_columns: false

# =============================================================================
# Model Configurations
# =============================================================================
models:
  employee_analytics:
    # Source layer - raw data ingestion
    source:
      +materialized: table
      +tags: ['source', 'daily']
    
    # Staging/Intermediate layer - data transformations
    staging:
      +materialized: incremental
      +incremental_strategy: merge
      +tags: ['staging', 'daily']
    
    # Mart layer - business-ready analytics tables
    mart:
      +materialized: incremental
      +tags: ['mart', 'daily']
    
    # Audit layer - observability and logging
    audit:
      +materialized: incremental
      +tags: ['audit', 'internal']

# =============================================================================
# Test Configuration
# =============================================================================
tests:
  employee_analytics:
    +severity: warn
    +store_failures: true

# =============================================================================
# On-Run Hooks
# =============================================================================
on-run-start:
  - "{{ log('Starting dbt run for employee_analytics', info=True) }}"

on-run-end:
  - "{{ log('Completed dbt run for employee_analytics', info=True) }}"
