version: 2

models:
  - name: mart_revenue_daily
    description: >
      Daily revenue aggregation by city with fiscal calendar attributes.
      All amounts converted to USD at transaction date.
    
    meta:
      problems_addressed:
        - "Currency Conversion"
        - "Fiscal Calendar"
        - "Conditional Aggregations"
    
    columns:
      - name: revenue_key
        tests:
          - unique
          - not_null
      - name: uber_net_revenue_usd
        description: Uber's net revenue after driver payouts
      - name: take_rate
        description: Uber's percentage of gross bookings

  - name: mart_driver_performance
    description: >
      Comprehensive driver performance metrics including
      lifetime stats, recent activity, and performance tiers.
    
    meta:
      problems_addressed:
        - "Cohort Analysis"
    
    columns:
      - name: driver_key
        tests:
          - unique
          - not_null
      - name: engagement_status
        tests:
          - accepted_values:
              values: ['ACTIVE', 'RECENT', 'AT_RISK', 'CHURNED']
      - name: performance_tier
        tests:
          - accepted_values:
              values: ['PLATINUM', 'GOLD', 'SILVER', 'BRONZE']

  - name: mart_reconciliation
    description: >
      Daily reconciliation report comparing trips to payments.
      Used for financial close and data quality monitoring.
    
    meta:
      problems_addressed:
        - "Data Reconciliation"
        - "Circuit Breaker"
    
    columns:
      - name: reconciliation_key
        tests:
          - unique
          - not_null
      - name: reconciliation_status
        tests:
          - accepted_values:
              values: ['RECONCILED', 'TRIPS_UNMATCHED', 'PAYMENTS_UNMATCHED', 'DISCREPANCY']
      - name: circuit_breaker_triggered
        description: True if match rate below threshold (99%)

